namespace SimpleOrm.Sample.Migrations;

/// <summary>Generated by simpleorm diff (ADR-0017); review the order before committing.</summary>
public sealed class V0009 : MigrationVersion
{
    public override void Compose(VersionBuilder version) => version
        .Apply<Table.UserProfile.V0009_AddUserProfiles>();
}
