namespace SimpleOrm.Sample.Migrations;

/// <summary>Generated by simpleorm diff (ADR-0017); review the order before committing.</summary>
public sealed class V0008 : MigrationVersion
{
    public override void Compose(VersionBuilder version) => version
        .Apply<Table.Role.V0008_AddRoleNameIndex>();
}
