package migrations

import (
	"github.com/kosmassp/SimpleOrm/go/orm"
	"github.com/kosmassp/SimpleOrm/go/orm/sample/migrations/Table/Role"
)

// V0008. Generated by simpleorm diff (ADR-0017); review the order before committing.
type V0008 struct{}

func (V0008) Compose(version *orm.VersionBuilder) {
	version.Apply(role.V0008_AddRoleNameIndex{})
}
