package migrations

import (
	"github.com/kosmassp/SimpleOrm/go/orm"
	"github.com/kosmassp/SimpleOrm/go/orm/sample/migrations/Table/UserProfile"
)

// V0009. Generated by simpleorm diff (ADR-0017); review the order before committing.
type V0009 struct{}

func (V0009) Compose(version *orm.VersionBuilder) {
	version.Apply(userprofile.V0009_AddUserProfiles{})
}
