<?php

declare(strict_types=1);

namespace SimpleOrm\Tests\Conformance;

use FilesystemIterator;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SimpleOrm\Dialect\SqliteDialect;
use SimpleOrm\Migrations\Diff\DiffCommand;
use SimpleOrm\Migrations\Diff\DiffOptions;
use SimpleOrm\Migrations\MigrationGenerator;
use SimpleOrm\Tests\Conformance\AmendFixture\AmendWidget;
use SimpleOrm\Tests\Support\ConformancePaths;

/**
 * The amend-case runner (§9, ADR-0017 add.3): each conformance/amend-cases/*.json
 * lays a migrations directory out as data — which files exist and whether they
 * carry the generator's header, which snapshots at which versions — runs
 * `DiffCommand::execute` (amend or plain) against the fixed fixture
 * ({@see AmendWidget}: V0001, V0002, one step each; model `id, name, remark`),
 * and checks the exit code, the files deleted, written, and kept, content
 * fragments, and output/error substrings. No database. Mirrors
 * `dotnet/tests/SimpleOrm.Tests/ConformanceAmendTests.cs`.
 *
 * The shared cases are language-neutral (amend-cases/README, ADR-0026): source
 * paths carry no extension and each implementation appends its own — `.php`
 * here — and `contains`/`omits` fragments are tokens (column names, storage
 * types, step class names, the generator header), never call syntax.
 */
final class AmendCasesTest extends TestCase
{
    private const string FIXTURE_DIR = __DIR__ . '/AmendFixture';

    private const string FIXTURE_NAMESPACE = 'SimpleOrm\\Tests\\Conformance\\AmendFixture';

    private const string EMPTY_NAMESPACE = 'SimpleOrm\\Tests\\Conformance\\AmendFixture\\NoSuchMigrations';

    private const string GENERATED_STEP_STUB =
        "<?php\n\n/** Generated by simpleorm diff (ADR-0017); conformance stub */\nfinal class Step\n{\n}\n";

    private const string HAND_WRITTEN_STUB =
        "<?php\n\n// hand-written: raw SQL nobody can diff back into existence\nfinal class Step\n{\n}\n";

    /** @return list<array{0: string}> */
    public static function caseFiles(): array
    {
        return array_map(static fn (string $file): array => [$file], ConformancePaths::cases('amend-cases'));
    }

    #[Test]
    #[DataProvider('caseFiles')]
    public function case_amends_as_specified(string $fileName): void
    {
        $spec = self::readJson(ConformancePaths::dir('amend-cases') . DIRECTORY_SEPARATOR . $fileName);
        $dir = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'simpleorm_amend_' . bin2hex(random_bytes(8));
        mkdir($dir, 0777, true);

        try {
            self::layFiles($dir, $spec);
            [$exit, $output, $error] = self::runDiff($dir, $spec);
            self::check($dir, $spec['expect'], $exit, $output, $error);
        } finally {
            self::removeDirectory($dir);
        }
    }

    // --- the tree as data -------------------------------------------------------------

    /** @param array<string, mixed> $spec */
    private static function layFiles(string $dir, array $spec): void
    {
        /** @var list<array{path: string, generated: bool, dialect?: string}> $files */
        $files = $spec['files'];
        $stepRefs = [];
        foreach ($files as $file) {
            if (str_contains($file['path'], '/')) {
                // Table/AmendWidget/V0002_AddNote -> SimpleOrm\Tests\...\Table\AmendWidget\V0002_AddNote
                $stepRefs[] = self::FIXTURE_NAMESPACE . '\\' . str_replace('/', '\\', $file['path']);
            }
        }

        foreach ($files as $file) {
            $relative = self::adaptPath($file['path']);
            $isRoot = !str_contains($file['path'], '/');
            $content = match (true) {
                $file['generated'] && $isRoot => MigrationGenerator::emitRoot(
                    self::FIXTURE_NAMESPACE,
                    (int) substr(pathinfo($file['path'], PATHINFO_FILENAME), 1),
                    $stepRefs,
                    $file['dialect'] ?? 'sqlite',
                ),
                $file['generated'] && !$isRoot => self::GENERATED_STEP_STUB,
                default => self::HAND_WRITTEN_STUB,
            };
            self::write($dir, $relative, $content);
        }

        /** @var list<array{path: string, snapshot: array<string, mixed>}> $snapshots */
        $snapshots = $spec['snapshots'];
        foreach ($snapshots as $snapshot) {
            self::write($dir, $snapshot['path'], json_encode($snapshot['snapshot'], JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
        }
    }

    /**
     * @param array<string, mixed> $spec
     * @return array{0: int, 1: string, 2: string}
     */
    private static function runDiff(string $dir, array $spec): array
    {
        $command = $spec['command'];
        $empty = ($spec['fixture'] ?? null) === 'none';
        $output = [];
        $error = [];

        $exit = DiffCommand::execute(
            new DiffOptions(
                migrationsDir: self::FIXTURE_DIR,
                rootNamespace: $empty ? self::EMPTY_NAMESPACE : self::FIXTURE_NAMESPACE,
                entityTypes: $empty ? [] : [AmendWidget::class],
                outDir: $dir,
                dialect: new SqliteDialect(),
                dialectLabel: $command['dialect'] ?? 'sqlite',
                name: $command['name'] ?? null,
                allowRemove: false,
                amend: $command['amend'] ?? false,
                force: $command['force'] ?? false,
                isApplied: ($command['applied'] ?? false) ? static fn (int $version): bool => true : null,
            ),
            static function (string $line) use (&$output): void {
                $output[] = $line;
            },
            static function (string $line) use (&$error): void {
                $error[] = $line;
            },
        );

        return [$exit, implode("\n", $output), implode("\n", $error)];
    }

    // --- what happened to the tree ------------------------------------------------------

    /** @param array<string, mixed> $expect */
    private static function check(string $dir, array $expect, int $exit, string $output, string $error): void
    {
        self::assertSame($expect['exit'], $exit);

        foreach (self::paths($expect, 'deleted') as $relative) {
            self::assertFileDoesNotExist(self::at($dir, $relative), "{$relative} should have been deleted");
        }

        foreach ([...self::paths($expect, 'written'), ...self::paths($expect, 'kept')] as $relative) {
            self::assertFileExists(self::at($dir, $relative), "{$relative} should exist");
        }

        /** @var list<array{path: string, contains?: list<string>, omits?: list<string>}> $files */
        $files = $expect['files'] ?? [];
        foreach ($files as $file) {
            $content = file_get_contents(self::at($dir, self::adaptPath($file['path'])));
            foreach (self::fragments($file, 'contains') as $fragment) {
                self::assertStringContainsString($fragment, $content);
            }

            foreach (self::fragments($file, 'omits') as $fragment) {
                self::assertStringNotContainsString($fragment, $content);
            }
        }

        foreach ($expect['output'] ?? [] as $fragment) {
            self::assertStringContainsString($fragment, $output);
        }

        foreach ($expect['error'] ?? [] as $fragment) {
            self::assertStringContainsString($fragment, $error);
        }

        if ($exit === 0) {
            self::assertSame('', $error);
        }
    }

    /** @param array<string, mixed> $expect @return list<string> */
    private static function paths(array $expect, string $key): array
    {
        return array_map(self::adaptPath(...), $expect[$key] ?? []);
    }

    /** @param array<string, mixed> $element @return list<string> */
    private static function fragments(array $element, string $key): array
    {
        return $element[$key] ?? [];
    }

    /**
     * Source paths in the shared cases carry no extension (amend-cases/README):
     * this port lays out and checks `.php` files; snapshot paths are literal.
     */
    private static function adaptPath(string $relative): string
    {
        return pathinfo($relative, PATHINFO_EXTENSION) === '' ? $relative . '.php' : $relative;
    }

    private static function at(string $dir, string $relative): string
    {
        return $dir . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relative);
    }

    private static function write(string $dir, string $relative, string $content): void
    {
        $path = self::at($dir, $relative);
        $parent = dirname($path);
        if (!is_dir($parent)) {
            mkdir($parent, 0777, true);
        }

        file_put_contents($path, $content);
    }

    /** @return array<string, mixed> */
    private static function readJson(string $path): array
    {
        /** @var array<string, mixed> $decoded */
        $decoded = json_decode(file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

        return $decoded;
    }

    private static function removeDirectory(string $dir): void
    {
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST,
        );
        foreach ($iterator as $fileInfo) {
            $fileInfo->isDir() ? rmdir($fileInfo->getPathname()) : unlink($fileInfo->getPathname());
        }

        rmdir($dir);
    }
}
