package role

import (
	"github.com/kosmassp/SimpleOrm/go/orm"
	"github.com/kosmassp/SimpleOrm/go/orm/sample"
)

// V0008_AddRoleNameIndex. Generated by simpleorm diff (ADR-0017); no Down —
// a runner derives the rollback from the snapshots (ADR-0018).
type V0008_AddRoleNameIndex struct {
	orm.TableMigration[sample.Role]
}

func (V0008_AddRoleNameIndex) Action(actions *orm.TableActions) {
	actions.SQL("create unique index if not exists ix_roles_role_name on roles (role_name)")
}
