<?php

declare(strict_types=1);

namespace SimpleOrm\Sample\Migrations\Table\UserProfile;

use SimpleOrm\Migrations\TableActions;
use SimpleOrm\Migrations\TableMigration;
use SimpleOrm\Sample\Models\Tables\UserProfile;

/** Mirrors a step generated by simpleorm diff (ADR-0017); no down: the runner derives the rollback from the snapshots (ADR-0018). */
final class V0009_AddUserProfiles extends TableMigration
{
    public function entityClass(): string
    {
        return UserProfile::class;
    }

    public function action(TableActions $actions): void
    {
        $actions->sql(<<<'SQL'
            create table if not exists user_profiles (
                id INTEGER PRIMARY KEY,
                user_id INTEGER NOT NULL,
                bio TEXT,
                avatar_url TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT
            ) STRICT
            SQL);
        $actions->sql('create unique index if not exists ix_user_profiles_user_id on user_profiles (user_id)');
    }
}
