// Package userprofile holds the user_profiles table's migration step,
// mirroring dotnet/samples/SimpleOrm.Sample/Migrations/Table/UserProfile
// (CLAUDE.md §7.22).
package userprofile

import (
	"github.com/kosmassp/SimpleOrm/go/orm"
	"github.com/kosmassp/SimpleOrm/go/orm/sample"
)

// V0009_AddUserProfiles. Generated by simpleorm diff (ADR-0017); no Down — a
// runner derives the rollback from the snapshots (ADR-0018).
type V0009_AddUserProfiles struct {
	orm.TableMigration[sample.UserProfile]
}

func (V0009_AddUserProfiles) Action(actions *orm.TableActions) {
	actions.SQL(`create table if not exists user_profiles (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT
) STRICT`)
	actions.SQL("create unique index if not exists ix_user_profiles_user_id on user_profiles (user_id)")
}
