<?php

declare(strict_types=1);

namespace SimpleOrm\Sample\Migrations\Table\Role;

use SimpleOrm\Migrations\TableActions;
use SimpleOrm\Migrations\TableMigration;
use SimpleOrm\Sample\Models\Tables\Role;

/** Mirrors a step generated by simpleorm diff (ADR-0017); no down: the runner derives the rollback from the snapshots (ADR-0018). */
final class V0008_AddRoleNameIndex extends TableMigration
{
    public function entityClass(): string
    {
        return Role::class;
    }

    public function action(TableActions $actions): void
    {
        $actions->sql('create unique index if not exists ix_roles_role_name on roles (role_name)');
    }
}
