<?php

declare(strict_types=1);

namespace SimpleOrm\Migrations;

use SimpleOrm\Dialect\Dialect;
use SimpleOrm\Metadata\EntityIndex;
use SimpleOrm\Metadata\EntityMap;
use SimpleOrm\Metadata\IndexColumn;

/**
 * The diff generator core (ADR-0017): compares entity metadata (the final
 * truth) against a table's latest committed snapshot and describes the
 * change; the emitters turn it into migration source with **no Down** — the
 * runner phase derives the rollback from the snapshots at `migrate down` time
 * (ADR-0018, `DownDeriver`). Renames are never inferred: they arrive as
 * explicit declarations. Type or nullability changes are not
 * auto-expressible (`DDL-004`) — those migrations are written by hand.
 */
final class MigrationGenerator
{
    /**
     * The ownership line every generated file carries. A future `diff --amend`
     * (ADR-0017 add.3) replaces only files that carry it — a hand-written
     * version is never overwritten by the tool.
     */
    public const string GENERATED_MARKER = 'Generated by simpleorm diff';

    private const string DIALECT_STAMP_PATTERN =
        '/Generated by simpleorm diff \(ADR-0017, dialect (?<label>[A-Za-z0-9_-]+)\)/';

    private function __construct()
    {
    }

    /** Whether the source was written by the generator (carries `GENERATED_MARKER`). */
    public static function isGenerated(string $source): bool
    {
        return str_contains($source, self::GENERATED_MARKER);
    }

    /**
     * The dialect a generated root was rendered for, from its header stamp —
     * or null for a root generated before dialect stamping existed. Storage
     * types are dialect-specific, so amending under another dialect refuses.
     */
    public static function generatedDialectLabel(string $source): ?string
    {
        return preg_match(self::DIALECT_STAMP_PATTERN, $source, $matches) === 1 ? $matches['label'] : null;
    }

    /** Diffs the entity's current metadata against the latest snapshot (null = new table). @param array<string, string> $renames declared old-column => new-column pairs */
    public static function diffMap(EntityMap $map, Dialect $dialect, ?TableSchema $snapshot, array $renames): TableDiff
    {
        return self::diff(SchemaSnapshot::fromMap($map, $dialect), $snapshot, $renames);
    }

    /**
     * The shape-vs-shape core: both sides in snapshot form, so the algorithm
     * is pure data — which is how the conformance diff cases exercise it.
     *
     * @param array<string, string> $renames declared old-column => new-column pairs
     */
    public static function diff(TableSchema $currentSchema, ?TableSchema $snapshot, array $renames): TableDiff
    {
        if ($snapshot === null) {
            return new TableDiff(isNew: true, added: [], removed: [], renamed: [], addedIndexSql: [], removedIndexNames: [], unsupported: []);
        }

        /** @var array<string, ColumnSpec> $old keyed by lowercased column name */
        $old = [];
        foreach ($snapshot->columns as $column) {
            $old[strtolower($column->name)] = new ColumnSpec($column->name, $column->storageType, $column->nullable);
        }

        /** @var array<string, ColumnSpec> $current keyed by lowercased column name */
        $current = [];
        foreach ($currentSchema->columns as $column) {
            $current[strtolower($column->name)] = new ColumnSpec($column->name, $column->storageType, $column->nullable);
        }

        $renamed = [];
        $unsupported = [];
        foreach ($renames as $from => $to) {
            $fromKey = strtolower($from);
            $toKey = strtolower($to);
            if (!isset($old[$fromKey])) {
                $unsupported[] = "rename {$from} -> {$to}: '{$from}' is not in the snapshot";

                continue;
            }

            if (!isset($current[$toKey])) {
                $unsupported[] = "rename {$from} -> {$to}: '{$to}' is not a mapped column";

                continue;
            }

            $renamed[] = new ColumnRename($from, $to);
            $renamedOld = $old[$fromKey];
            unset($old[$fromKey]);
            $old[$toKey] = new ColumnSpec($to, $renamedOld->storageType, $renamedOld->nullable);
        }

        $added = [];
        foreach ($current as $key => $column) {
            if (isset($old[$key])) {
                continue;
            }

            if ($column->nullable) {
                $added[] = $column;
            } else {
                $unsupported[] = "add {$column->name}: non-nullable additions need a default/backfill — write the migration by hand";
            }
        }

        $removed = [];
        foreach ($old as $key => $column) {
            if (!isset($current[$key])) {
                $removed[] = $column;
            }
        }

        foreach ($current as $key => $after) {
            if (!isset($old[$key])) {
                continue;
            }

            $before = $old[$key];
            if (strcasecmp($before->storageType, $after->storageType) !== 0 || $before->nullable !== $after->nullable) {
                $beforeLabel = $before->storageType . ($before->nullable ? '' : ' not null');
                $afterLabel = $after->storageType . ($after->nullable ? '' : ' not null');
                $unsupported[] = "column {$after->name}: {$beforeLabel} -> {$afterLabel} — write the migration by hand";
            }
        }

        // Indexes match by structure — unique flag plus ordered (column, direction) —
        // never by name (ADR-0017 add.2): indexes get added directly to the database
        // in urgencies, and one that exists under another name is implemented.
        $oldSignatures = [];
        foreach ($snapshot->indexes as $index) {
            $oldSignatures[self::indexSignature($index)] = true;
        }

        $modelSignatures = [];
        foreach ($currentSchema->indexes as $index) {
            $modelSignatures[self::indexSignature($index)] = true;
        }

        $addedIndexSql = [];
        foreach ($currentSchema->indexes as $index) {
            if (!isset($oldSignatures[self::indexSignature($index)])) {
                $addedIndexSql[] = SnapshotDdl::createIndexSql($currentSchema->name, $index);
            }
        }

        $removedIndexNames = [];
        foreach ($snapshot->indexes as $index) {
            if (!isset($modelSignatures[self::indexSignature($index)])) {
                $removedIndexNames[] = $index->name;
            }
        }

        return new TableDiff(
            isNew: false,
            added: array_values($added),
            removed: array_values($removed),
            renamed: $renamed,
            addedIndexSql: $addedIndexSql,
            removedIndexNames: $removedIndexNames,
            unsupported: $unsupported,
        );
    }

    /** The structural identity of a declared or snapshotted/introspected index: unique + ordered columns with direction. */
    public static function indexSignature(EntityIndex|TableSchemaIndex $index): string
    {
        $columns = $index instanceof EntityIndex
            ? array_map(static fn (IndexColumn $c): array => [$c->columnName, $c->descending], $index->columns)
            : array_map(static fn (TableSchemaIndexPart $c): array => [$c->columnName, $c->descending], $index->columns);

        return self::signature($index->unique, $columns);
    }

    /** @param list<array{0: string, 1: bool}> $columns (column name, descending) pairs, in order */
    public static function signature(bool $unique, array $columns): string
    {
        $parts = array_map(
            static fn (array $c): string => strtolower($c[0]) . ($c[1] ? ' desc' : ''),
            $columns,
        );

        return ($unique ? 'unique|' : 'plain|') . implode(',', $parts);
    }

    /** Emits the per-object migration step source. No Down — the runner phase derives the rollback from the snapshots (ADR-0018). */
    public static function emitTableStep(
        string $rootNamespace,
        string $entityClass,
        EntityMap $map,
        Dialect $dialect,
        int $version,
        string $description,
        TableDiff $diff,
    ): string {
        $shortName = self::shortName($entityClass);
        $className = 'V' . sprintf('%04d', $version) . '_' . $description;

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            "namespace {$rootNamespace}\\Table\\{$shortName};",
            '',
            '/**',
            ' * Generated by simpleorm diff (ADR-0017); no Down — the runner derives the rollback from the snapshots (ADR-0018).',
            ' */',
            "final class {$className} extends \\SimpleOrm\\Migrations\\TableMigration",
            '{',
            '    public function entityClass(): string',
            '    {',
            "        return \\{$entityClass}::class;",
            '    }',
            '',
            '    public function action(\\SimpleOrm\\Migrations\\TableActions $actions): void',
            '    {',
        ];

        if ($diff->isNew) {
            self::appendSqlAction($lines, $dialect->createTableSql($map));
            foreach ($dialect->createIndexSql($map) as $indexSql) {
                self::appendSqlAction($lines, $indexSql);
            }
        } else {
            foreach ($diff->renamed as $rename) {
                $lines[] = "        \$actions->renameColumn('" . self::escapeSingleQuoted($rename->from) . "', '"
                    . self::escapeSingleQuoted($rename->to) . "');";
            }

            foreach ($diff->added as $column) {
                $lines[] = "        \$actions->addColumn('" . self::escapeSingleQuoted($column->name) . "', '"
                    . self::escapeSingleQuoted($column->storageType) . "');";
            }

            foreach ($diff->removed as $column) {
                $lines[] = "        \$actions->removeColumn('" . self::escapeSingleQuoted($column->name) . "');";
            }

            foreach ($diff->addedIndexSql as $indexSql) {
                self::appendSqlAction($lines, $indexSql);
            }

            foreach ($diff->removedIndexNames as $name) {
                $lines[] = "        \$actions->dropIndex('" . self::escapeSingleQuoted($name) . "');";
            }
        }

        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Emits a view/materialized-view step from **literal DDL** (never
     * metadata-rendered, so the applied step's checksum can never drift when
     * the definition changes again). A change opens with the
     * expected-previous-definition guard (`MIG-012` on outside drift). No
     * Down is emitted — the runner phase derives the rollback (guard, drop,
     * previous definition) from the DDL snapshots (ADR-0018).
     */
    public static function emitViewStep(
        string $rootNamespace,
        string $entityClass,
        string $kindFolder,
        string $objectName,
        int $version,
        string $description,
        string $createDdl,
        ?string $previousDdl,
    ): string {
        $shortName = self::shortName($entityClass);
        $className = 'V' . sprintf('%04d', $version) . '_' . $description;
        $dropSql = ($kindFolder === 'MaterializedView' ? 'drop materialized view if exists ' : 'drop view if exists ') . $objectName;

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            "namespace {$rootNamespace}\\{$kindFolder}\\{$shortName};",
            '',
            '/**',
            ' * Generated by simpleorm diff (ADR-0017): literal DDL, guarded by the expected previous definition'
                . ' (MIG-012 on outside drift); the rollback derives from the snapshots (ADR-0018).',
            ' */',
            "final class {$className} extends \\SimpleOrm\\Migrations\\ViewMigration",
            '{',
            '    public function entityClass(): string',
            '    {',
            "        return \\{$entityClass}::class;",
            '    }',
            '',
            '    public function action(\\SimpleOrm\\Migrations\\ViewActions $actions): void',
            '    {',
        ];

        if ($previousDdl !== null) {
            self::appendViewAction($lines, 'expectDefinition', $previousDdl);
            self::appendViewAction($lines, 'sql', $dropSql);
        }

        self::appendViewAction($lines, 'sql', $createDdl);

        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Emits the root version composing the steps in the given order. The
     * header stamps the dialect (`$dialectLabel`, the future CLI's
     * `--dialect` name): the recorded unit remembers what its storage types
     * were rendered for, so a future `diff --amend` can refuse a dialect
     * switch.
     *
     * @param list<class-string> $stepClasses fully qualified step class names, in composition order
     */
    public static function emitRoot(string $rootNamespace, int $version, array $stepClasses, string $dialectLabel): string
    {
        $className = 'V' . sprintf('%04d', $version);

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            "namespace {$rootNamespace};",
            '',
            '/**',
            " * Generated by simpleorm diff (ADR-0017, dialect {$dialectLabel}); review the order before committing.",
            ' */',
            "final class {$className} extends \\SimpleOrm\\Migrations\\MigrationVersion",
            '{',
            '    public function compose(\\SimpleOrm\\Migrations\\VersionBuilder $version): void',
            '    {',
            '        $version',
        ];

        $last = count($stepClasses) - 1;
        foreach ($stepClasses as $i => $stepClass) {
            $lines[] = "            ->apply(\\{$stepClass}::class)" . ($i === $last ? ';' : '');
        }

        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /** @param list<string> $lines */
    private static function appendSqlAction(array &$lines, string $sql): void
    {
        if (!str_contains($sql, "\n")) {
            $lines[] = "        \$actions->sql('" . self::escapeSingleQuoted($sql) . "');";

            return;
        }

        $lines[] = "        \$actions->sql(<<<'SQL'";
        foreach (explode("\n", str_replace("\r", '', $sql)) as $line) {
            $lines[] = $line;
        }

        $lines[] = 'SQL';
        $lines[] = '        );';
    }

    /** @param list<string> $lines */
    private static function appendViewAction(array &$lines, string $method, string $sql): void
    {
        $lines[] = "        \$actions->{$method}('" . self::escapeSingleQuoted($sql) . "');";
    }

    private static function escapeSingleQuoted(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }

    private static function shortName(string $fqcn): string
    {
        $pos = strrpos($fqcn, '\\');

        return $pos === false ? $fqcn : substr($fqcn, $pos + 1);
    }
}
