package migrations

import (
	"fmt"
	"go/format"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/kosmassp/SimpleOrm/go/orm/internal/core"
)

// GeneratedMarker is the ownership line every generated file carries. A
// (future) `diff --amend` replaces only files that carry it — a hand-written
// version is never overwritten by the tool.
const GeneratedMarker = "Generated by simpleorm diff"

var dialectStampPattern = regexp.MustCompile(`Generated by simpleorm diff \(ADR-0017, dialect ([A-Za-z0-9_-]+)\)`)

// IsGenerated reports whether source was written by the generator (carries GeneratedMarker).
func IsGenerated(source string) bool {
	return strings.Contains(source, GeneratedMarker)
}

// GeneratedDialectLabel is the dialect a generated root was rendered for, from
// its header stamp — "" for a root generated before dialect stamping existed,
// or for a non-root/hand-written file. Storage types are dialect-specific, so
// amending under another dialect must refuse.
func GeneratedDialectLabel(source string) string {
	match := dialectStampPattern.FindStringSubmatch(source)
	if match == nil {
		return ""
	}
	return match[1]
}

// ColumnSpec is a column's name, storage type, and nullability — the shape
// diffed between two schemas.
type ColumnSpec struct {
	Name        string
	StorageType string
	Nullable    bool
}

// TableDiff is the generator's diff core: the metadata-vs-snapshot shape (ADR-0017).
type TableDiff struct {
	IsNew             bool
	Added             []ColumnSpec
	Removed           []ColumnSpec
	Renamed           []ColumnRename
	AddedIndexSQL     []string
	RemovedIndexNames []string
	// Unsupported entries name a change the generator cannot express safely
	// (DDL-004: a same-column type/nullability change, or a non-nullable
	// addition) — those migrations are written by hand.
	Unsupported []string
}

// HasChanges reports whether the diff has anything to emit.
func (d *TableDiff) HasChanges() bool {
	return d.IsNew || len(d.Added) > 0 || len(d.Removed) > 0 || len(d.Renamed) > 0 ||
		len(d.AddedIndexSQL) > 0 || len(d.RemovedIndexNames) > 0
}

// Diff diffs m's current shape against snapshot (nil = new table); renames maps old column name -> new column name.
func Diff(m *core.EntityMap, dialect core.Dialect, snapshot *TableSchema, renames map[string]string) *TableDiff {
	return DiffSchemas(FromMap(m, dialect), snapshot, renames)
}

// DiffSchemas is the shape-vs-shape core: both sides already in snapshot
// form, so the algorithm is pure data — what the conformance diff-cases
// exercise directly.
func DiffSchemas(current, snapshot *TableSchema, renames map[string]string) *TableDiff {
	if snapshot == nil {
		return &TableDiff{IsNew: true}
	}

	diff := &TableDiff{}

	oldOrder := make([]string, 0, len(snapshot.Columns))
	oldByKey := make(map[string]ColumnSpec, len(snapshot.Columns))
	for _, c := range snapshot.Columns {
		key := strings.ToLower(c.Name)
		oldOrder = append(oldOrder, key)
		oldByKey[key] = ColumnSpec{Name: c.Name, StorageType: c.StorageType, Nullable: c.Nullable}
	}
	currentByKey := make(map[string]ColumnSpec, len(current.Columns))
	for _, c := range current.Columns {
		currentByKey[strings.ToLower(c.Name)] = ColumnSpec{Name: c.Name, StorageType: c.StorageType, Nullable: c.Nullable}
	}

	// Renames are declared, never inferred; applied in a stable (sorted) order
	// so a diff over a Go map is deterministic.
	fromNames := make([]string, 0, len(renames))
	for from := range renames {
		fromNames = append(fromNames, from)
	}
	sort.Strings(fromNames)
	for _, from := range fromNames {
		to := renames[from]
		fromKey, toKey := strings.ToLower(from), strings.ToLower(to)
		oldColumn, hasOld := oldByKey[fromKey]
		if !hasOld {
			diff.Unsupported = append(diff.Unsupported, fmt.Sprintf("rename %s -> %s: '%s' is not in the snapshot", from, to, from))
			continue
		}
		if _, hasCurrent := currentByKey[toKey]; !hasCurrent {
			diff.Unsupported = append(diff.Unsupported, fmt.Sprintf("rename %s -> %s: '%s' is not a mapped column", from, to, to))
			continue
		}
		diff.Renamed = append(diff.Renamed, ColumnRename{From: from, To: to})
		delete(oldByKey, fromKey)
		oldByKey[toKey] = ColumnSpec{Name: to, StorageType: oldColumn.StorageType, Nullable: oldColumn.Nullable}
		for i, key := range oldOrder {
			if key == fromKey {
				oldOrder[i] = toKey
				break
			}
		}
	}

	for _, c := range current.Columns {
		key := strings.ToLower(c.Name)
		if _, exists := oldByKey[key]; exists {
			continue
		}
		column := currentByKey[key]
		if !column.Nullable {
			diff.Unsupported = append(diff.Unsupported, fmt.Sprintf(
				"add %s: non-nullable additions need a default/backfill — write the migration by hand", column.Name))
		} else {
			diff.Added = append(diff.Added, column)
		}
	}

	for _, key := range oldOrder {
		if _, exists := currentByKey[key]; !exists {
			diff.Removed = append(diff.Removed, oldByKey[key])
		}
	}

	for _, c := range current.Columns {
		key := strings.ToLower(c.Name)
		before, existed := oldByKey[key]
		if !existed {
			continue
		}
		after := currentByKey[key]
		if !strings.EqualFold(before.StorageType, after.StorageType) || before.Nullable != after.Nullable {
			diff.Unsupported = append(diff.Unsupported, fmt.Sprintf(
				"column %s: %s%s -> %s%s — write the migration by hand",
				c.Name, before.StorageType, nullSuffix(before.Nullable), after.StorageType, nullSuffix(after.Nullable)))
		}
	}

	// Indexes match structurally — unique flag + ordered (column, direction) —
	// never by name (ADR-0017 add.2): one added directly to the database under
	// another name counts as implemented.
	oldSignatures := map[string]bool{}
	for _, index := range snapshot.Indexes {
		oldSignatures[IndexSignature(index)] = true
	}
	currentSignatures := map[string]bool{}
	for _, index := range current.Indexes {
		currentSignatures[IndexSignature(index)] = true
	}
	for _, index := range current.Indexes {
		if !oldSignatures[IndexSignature(index)] {
			diff.AddedIndexSQL = append(diff.AddedIndexSQL, CreateIndexSQL(current.Name, index))
		}
	}
	for _, index := range snapshot.Indexes {
		if !currentSignatures[IndexSignature(index)] {
			diff.RemovedIndexNames = append(diff.RemovedIndexNames, index.Name)
		}
	}

	return diff
}

func nullSuffix(nullable bool) string {
	if nullable {
		return ""
	}
	return " not null"
}

// IndexSignature is the structural identity of a snapshotted or introspected
// index: unique flag + ordered (column, direction) — never the name.
func IndexSignature(index TableIndex) string {
	columns := make([]indexSignatureColumn, len(index.Columns))
	for i, c := range index.Columns {
		columns[i] = indexSignatureColumn{c.ColumnName, c.Descending}
	}
	return indexSignature(index.Unique, columns)
}

// EntityIndexSignature is the same structural identity for a declared metadata index.
func EntityIndexSignature(index *core.EntityIndex) string {
	columns := make([]indexSignatureColumn, len(index.Columns))
	for i, c := range index.Columns {
		columns[i] = indexSignatureColumn{c.ColumnName, c.Descending}
	}
	return indexSignature(index.Unique, columns)
}

type indexSignatureColumn struct {
	column     string
	descending bool
}

func indexSignature(unique bool, columns []indexSignatureColumn) string {
	kind := "plain|"
	if unique {
		kind = "unique|"
	}
	parts := make([]string, len(columns))
	for i, c := range columns {
		part := strings.ToLower(c.column)
		if c.descending {
			part += " desc"
		}
		parts[i] = part
	}
	return kind + strings.Join(parts, ",")
}

// --- Go-source emitters ------------------------------------------------

const ormImportPath = "github.com/kosmassp/SimpleOrm/go/orm"

// packageAlias is an import path's last path element — the deterministic
// alias every emitted import gets, since the emitter has only the path
// (reflect.Type.PkgPath()), never the target file's actual `package` clause.
func packageAlias(importPath string) string {
	if idx := strings.LastIndexByte(importPath, '/'); idx >= 0 {
		return importPath[idx+1:]
	}
	return importPath
}

// goStringLiteral renders sql as a Go string literal: a backquoted raw string
// when sql contains no backtick (readable multi-line SQL stays literal),
// else a quoted, escaped string.
func goStringLiteral(sql string) string {
	if !strings.Contains(sql, "`") {
		return "`" + sql + "`"
	}
	return strconv.Quote(sql)
}

func importBlock(imports map[string]string) string {
	type importLine struct{ alias, path string }
	lines := make([]importLine, 0, len(imports))
	for alias, path := range imports {
		lines = append(lines, importLine{alias, path})
	}
	sort.Slice(lines, func(i, j int) bool { return lines[i].path < lines[j].path })
	var b strings.Builder
	for _, l := range lines {
		fmt.Fprintf(&b, "\t%s %q\n", l.alias, l.path)
	}
	return b.String()
}

func formatGoSource(source string) (string, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("generated source does not parse: %w\n---\n%s", err, source)
	}
	return string(formatted), nil
}

// EmitTableStep emits one table step's Go source (destined for
// Table/<Object>/V000N_<Description>.go): package <lowercase entity type
// name>, importing orm and the entity's own package (aliased to its import
// path's last element), declaring the step type embedding
// orm.TableMigration[<entity>] with an Action built from diff — the create
// (diff.IsNew, rendered from m/dialect like the reference) or the
// rename/add/remove/index actions. No Down is emitted: a (future) runner
// derives the rollback from the snapshots (ADR-0018).
func EmitTableStep(m *core.EntityMap, dialect core.Dialect, version int64, description string, diff *TableDiff) (string, error) {
	entityType := m.Type
	entityImportPath := entityType.PkgPath()
	entityAlias := packageAlias(entityImportPath)
	typeName := fmt.Sprintf("V%04d_%s", version, description)
	pkgName := strings.ToLower(entityType.Name())

	var body strings.Builder
	if diff.IsNew {
		fmt.Fprintf(&body, "\tactions.SQL(%s)\n", goStringLiteral(dialect.CreateTableSQL(m)))
		for _, indexSQL := range dialect.CreateIndexSQL(m) {
			fmt.Fprintf(&body, "\tactions.SQL(%s)\n", goStringLiteral(indexSQL))
		}
	} else {
		for _, rename := range diff.Renamed {
			fmt.Fprintf(&body, "\tactions.RenameColumn(%s, %s)\n", strconv.Quote(rename.From), strconv.Quote(rename.To))
		}
		for _, column := range diff.Added {
			fmt.Fprintf(&body, "\tactions.AddColumn(%s, %s)\n", strconv.Quote(column.Name), strconv.Quote(column.StorageType))
		}
		for _, column := range diff.Removed {
			fmt.Fprintf(&body, "\tactions.RemoveColumn(%s)\n", strconv.Quote(column.Name))
		}
		for _, indexSQL := range diff.AddedIndexSQL {
			fmt.Fprintf(&body, "\tactions.SQL(%s)\n", goStringLiteral(indexSQL))
		}
		for _, name := range diff.RemovedIndexNames {
			fmt.Fprintf(&body, "\tactions.DropIndex(%s)\n", strconv.Quote(name))
		}
	}

	imports := importBlock(map[string]string{entityAlias: entityImportPath, "orm": ormImportPath})
	source := fmt.Sprintf(
		"// %s (ADR-0017); no Down -- a runner derives the rollback from the snapshots (ADR-0018).\n"+
			"package %s\n\nimport (\n%s)\n\ntype %s struct {\n\torm.TableMigration[%s.%s]\n}\n\n"+
			"func (%s) Action(actions *orm.TableActions) {\n%s}\n",
		GeneratedMarker, pkgName, imports, typeName, entityAlias, entityType.Name(), typeName, body.String())
	return formatGoSource(source)
}

// EmitViewStep emits one view (or materialized view) step's Go source from
// **literal DDL** (never metadata-rendered, so the applied step's checksum
// can never drift when the definition changes again). previousDDL nil means a
// new view (no guard); non-nil emits the ExpectDefinition(previousDDL) guard
// first (MIG-012 on outside drift), followed by the drop and the create.
func EmitViewStep(
	entityType reflect.Type, materialized bool, objectName string,
	version int64, description string, createDDL string, previousDDL *string,
) (string, error) {
	entityImportPath := entityType.PkgPath()
	entityAlias := packageAlias(entityImportPath)
	typeName := fmt.Sprintf("V%04d_%s", version, description)
	pkgName := strings.ToLower(entityType.Name())

	dropSQL := "drop view if exists " + objectName
	if materialized {
		dropSQL = "drop materialized view if exists " + objectName
	}

	var body strings.Builder
	if previousDDL != nil {
		fmt.Fprintf(&body, "\tactions.ExpectDefinition(%s)\n", goStringLiteral(*previousDDL))
		fmt.Fprintf(&body, "\tactions.SQL(%s)\n", goStringLiteral(dropSQL))
	}
	fmt.Fprintf(&body, "\tactions.SQL(%s)\n", goStringLiteral(createDDL))

	imports := importBlock(map[string]string{entityAlias: entityImportPath, "orm": ormImportPath})
	source := fmt.Sprintf(
		"// %s (ADR-0017): literal DDL, guarded by the expected previous definition\n"+
			"// (MIG-012 on outside drift); the rollback derives from the snapshots (ADR-0018).\n"+
			"package %s\n\nimport (\n%s)\n\ntype %s struct {\n\torm.ViewMigration[%s.%s]\n}\n\n"+
			"func (%s) Action(actions *orm.ViewActions) {\n%s}\n",
		GeneratedMarker, pkgName, imports, typeName, entityAlias, entityType.Name(), typeName, body.String())
	return formatGoSource(source)
}

// RootStepRef identifies one step a generated root composes: the step
// package's import path and name, and the step type it applies.
type RootStepRef struct {
	ImportPath string
	Package    string
	TypeName   string
}

// EmitRoot emits the root version composing steps in the given order
// (destined for <migrationsPackage>/V000N.go): package <last element of
// migrationsPackage>, importing orm and each step's package, declaring
// `type V000N struct{}` with Compose applying the steps in order. The header
// stamps the dialect: the recorded unit remembers what its storage types were
// rendered for, so a (future) `diff --amend` can refuse a dialect switch.
func EmitRoot(migrationsPackage string, version int64, steps []RootStepRef, dialectLabel string) (string, error) {
	rootPackage := packageAlias(migrationsPackage)
	typeName := fmt.Sprintf("V%04d", version)

	imports := map[string]string{"orm": ormImportPath}
	for _, step := range steps {
		imports[step.Package] = step.ImportPath
	}

	var body strings.Builder
	fmt.Fprintf(&body, "func (%s) Compose(version *orm.VersionBuilder) {\n\tversion.\n", typeName)
	for i, step := range steps {
		fmt.Fprintf(&body, "\t\tApply(%s.%s{})", step.Package, step.TypeName)
		if i < len(steps)-1 {
			body.WriteString(".")
		}
		body.WriteString("\n")
	}
	body.WriteString("}\n")

	source := fmt.Sprintf(
		"// %s (ADR-0017, dialect %s); review the order before committing.\n"+
			"package %s\n\nimport (\n%s)\n\ntype %s struct{}\n\n%s",
		GeneratedMarker, dialectLabel, rootPackage, importBlock(imports), typeName, body.String())
	return formatGoSource(source)
}
