namespace SimpleOrm.Sample.Migrations.Table.Role;

/// <summary>Generated by simpleorm diff (ADR-0017); the Down derives from the previous snapshot.</summary>
public sealed class V0008_AddRoleNameIndex : TableMigration<global::SimpleOrm.Sample.Models.Role>
{
    public override void Action(TableActions actions)
    {
        actions.Sql("create unique index if not exists ix_roles_role_name on roles (role_name)");
    }

    public override void Down(TableActions actions)
    {
        actions.DropIndex("ix_roles_role_name");
    }
}
