namespace SimpleOrm.Sample.Migrations.Table.Role;

/// <summary>Generated by simpleorm diff (ADR-0017); no Down — the runner derives the rollback from the snapshots (ADR-0018).</summary>
public sealed class V0008_AddRoleNameIndex : TableMigration<global::SimpleOrm.Sample.Models.Role>
{
    public override void Action(TableActions actions)
    {
        actions.Sql("create unique index if not exists ix_roles_role_name on roles (role_name)");
    }
}
