<?php

declare(strict_types=1);

namespace SimpleOrm\Sample\Migrations;

use SimpleOrm\Migrations\MigrationVersion;
use SimpleOrm\Migrations\VersionBuilder;
use SimpleOrm\Sample\Migrations\Table\Role\V0008_AddRoleNameIndex;

/** Mirrors a version generated by simpleorm diff (ADR-0017); review the order before committing. */
final class V0008 extends MigrationVersion
{
    public function compose(VersionBuilder $version): void
    {
        $version
            ->apply(V0008_AddRoleNameIndex::class);
    }
}
