<?php

declare(strict_types=1);

namespace SimpleOrm\Sample\Migrations;

use SimpleOrm\Migrations\MigrationVersion;
use SimpleOrm\Migrations\VersionBuilder;
use SimpleOrm\Sample\Migrations\Table\UserProfile\V0009_AddUserProfiles;

/** Mirrors a version generated by simpleorm diff (ADR-0017); review the order before committing. */
final class V0009 extends MigrationVersion
{
    public function compose(VersionBuilder $version): void
    {
        $version
            ->apply(V0009_AddUserProfiles::class);
    }
}
