namespace SimpleOrm.Sample.Migrations.Table.UserProfile;

/// <summary>Generated by simpleorm diff (ADR-0017); no Down — the runner derives the rollback from the snapshots (ADR-0018).</summary>
public sealed class V0009_AddUserProfiles : TableMigration<global::SimpleOrm.Sample.Models.UserProfile>
{
    public override void Action(TableActions actions)
    {
        actions.Sql(
            """
            create table if not exists user_profiles (
                id INTEGER PRIMARY KEY,
                user_id INTEGER NOT NULL,
                bio TEXT,
                avatar_url TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT
            ) STRICT
            """);
        actions.Sql("create unique index if not exists ix_user_profiles_user_id on user_profiles (user_id)");
    }
}
