using System.Text.Json;
using SimpleOrm.Cli;
using SimpleOrm.Sqlite;
using SimpleOrm.Tests.AmendFixture;
using Xunit;

namespace SimpleOrm.Tests;

/// <summary>
/// The amend-case runner (§9, ADR-0017 add.3): each conformance/amend-cases/*.json
/// lays a migrations directory out as data — which files exist and whether they
/// carry the generator's header, which snapshots at which versions — runs
/// <c>diff</c> (amend or plain) through the CLI's command class against the
/// fixed fixture (<see cref="AmendWidget"/>: V0001, V0002, one step each; model
/// <c>id, name, remark</c>), and checks the exit code, the files deleted, written,
/// and kept, content fragments, and output/error substrings. No database.
/// </summary>
public sealed class ConformanceAmendTests
{
    private const string FixtureNamespace = "SimpleOrm.Tests.AmendFixture";
    private const string EmptyNamespace = "SimpleOrm.Tests.NoSuchMigrations";

    private const string GeneratedStepStub =
        "/// <summary>Generated by simpleorm diff (ADR-0017); conformance stub</summary>\npublic sealed class Step { }\n";

    private const string HandWrittenStub = "// hand-written: raw SQL nobody can diff back into existence\npublic sealed class Step { }\n";

    public static TheoryData<string> CaseFiles
    {
        get
        {
            var data = new TheoryData<string>();
            foreach (var file in Directory.GetFiles(
                Path.Combine(ConformanceMigrationTests.ConformanceDirectory(), "amend-cases"), "*.json"))
            {
                data.Add(Path.GetFileName(file));
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(CaseFiles))]
    public async Task Case_amends_as_specified(string fileName)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(
            Path.Combine(ConformanceMigrationTests.ConformanceDirectory(), "amend-cases", fileName)));
        var spec = document.RootElement;
        var dir = Path.Combine(Path.GetTempPath(), $"simpleorm_amend_{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        try
        {
            LayFiles(dir, spec);
            var (exit, output, error) = await RunAsync(dir, spec);
            Check(dir, spec.GetProperty("expect"), exit, output, error);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    // --- the tree as data ------------------------------------------------------------

    private static void LayFiles(string dir, JsonElement spec)
    {
        var files = spec.GetProperty("files").EnumerateArray().ToArray();
        var stepRefs = files
            .Select(f => f.GetProperty("path").GetString()!)
            .Where(p => p.Contains('/'))
            .Select(p => p.Replace('/', '.')[..^".cs".Length])   // Table/AmendWidget/V0002_AddNote.cs → Table.AmendWidget.V0002_AddNote
            .ToArray();

        foreach (var file in files)
        {
            var relative = file.GetProperty("path").GetString()!;
            var generated = file.GetProperty("generated").GetBoolean();
            var isRoot = !relative.Contains('/');
            var content = (generated, isRoot) switch
            {
                (true, true) => MigrationGenerator.EmitRoot(
                    FixtureNamespace,
                    long.Parse(Path.GetFileNameWithoutExtension(relative)[1..]),
                    stepRefs,
                    file.TryGetProperty("dialect", out var dialect) ? dialect.GetString()! : "sqlite"),
                (true, false) => GeneratedStepStub,
                _ => HandWrittenStub,
            };
            Write(dir, relative, content);
        }

        foreach (var snapshot in spec.GetProperty("snapshots").EnumerateArray())
        {
            Write(dir, snapshot.GetProperty("path").GetString()!, snapshot.GetProperty("snapshot").GetRawText());
        }
    }

    private static async Task<(int Exit, string Output, string Error)> RunAsync(string dir, JsonElement spec)
    {
        var command = spec.GetProperty("command");
        var empty = spec.TryGetProperty("fixture", out var fixture) && fixture.GetString() == "none";
        var output = new StringWriter();
        var error = new StringWriter();
        var exit = await DiffCommand.ExecuteAsync(
            new DiffOptions
            {
                Assembly = typeof(ConformanceAmendTests).Assembly,
                EntityTypes = empty ? [] : [typeof(AmendWidget)],
                OutDir = dir,
                RootNamespace = empty ? EmptyNamespace : FixtureNamespace,
                Dialect = new SqliteDialect(),
                DialectLabel = command.TryGetProperty("dialect", out var dialect) ? dialect.GetString()! : "sqlite",
                Name = command.TryGetProperty("name", out var name) ? name.GetString() : null,
                Amend = Flag(command, "amend"),
                Force = Flag(command, "force"),
                IsApplied = Flag(command, "applied") ? _ => Task.FromResult(true) : null,
            },
            output,
            error);
        return (exit, output.ToString(), error.ToString());
    }

    // --- what happened to the tree ----------------------------------------------------

    private static void Check(string dir, JsonElement expect, int exit, string output, string error)
    {
        Assert.Equal(expect.GetProperty("exit").GetInt32(), exit);

        foreach (var relative in Strings(expect, "deleted"))
        {
            Assert.False(File.Exists(At(dir, relative)), $"{relative} should have been deleted");
        }

        foreach (var relative in Strings(expect, "written").Concat(Strings(expect, "kept")))
        {
            Assert.True(File.Exists(At(dir, relative)), $"{relative} should exist");
        }

        if (expect.TryGetProperty("files", out var files))
        {
            foreach (var file in files.EnumerateArray())
            {
                var content = File.ReadAllText(At(dir, file.GetProperty("path").GetString()!));
                foreach (var fragment in Strings(file, "contains"))
                {
                    Assert.Contains(fragment, content);
                }

                foreach (var fragment in Strings(file, "omits"))
                {
                    Assert.DoesNotContain(fragment, content);
                }
            }
        }

        foreach (var fragment in Strings(expect, "output"))
        {
            Assert.Contains(fragment, output);
        }

        foreach (var fragment in Strings(expect, "error"))
        {
            Assert.Contains(fragment, error);
        }

        if (exit == 0)
        {
            Assert.Equal(string.Empty, error);
        }
    }

    private static bool Flag(JsonElement element, string name)
        => element.TryGetProperty(name, out var value) && value.GetBoolean();

    private static IEnumerable<string> Strings(JsonElement element, string name)
        => element.TryGetProperty(name, out var value)
            ? value.EnumerateArray().Select(v => v.GetString()!).ToArray()
            : [];

    private static string At(string dir, string relative)
        => Path.Combine(dir, relative.Replace('/', Path.DirectorySeparatorChar));

    private static void Write(string dir, string relative, string content)
    {
        var path = At(dir, relative);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }
}
