using SimpleOrm.Postgres;
using SimpleOrm.Sample.Models;
using Xunit;

namespace SimpleOrm.Tests;

/// <summary>
/// Pure rendering tests for <see cref="PostgresDialect"/> (ADR-0025) — no
/// database; live behavior is covered by <see cref="PostgresIntegrationTests"/>.
/// </summary>
public sealed class PostgresDialectTests
{
    private static readonly PostgresDialect Dialect = new();
    private static readonly EntityMapLoader Maps = new();

    private static string Render(SelectAst ast, List<object?> bound)
        => Dialect.SelectSql(ast, (value, _) =>
        {
            bound.Add(value);
            return "@c" + (bound.Count - 1);
        });

    [Fact]
    public void Quotes_double_quotes_and_escapes()
    {
        Assert.Equal("\"order\"", Dialect.QuoteIdentifier("order"));
        Assert.Equal("\"odd\"\"name\"", Dialect.QuoteIdentifier("odd\"name"));
    }

    [Fact]
    public void Create_table_renders_identity_key_and_native_types()
    {
        var sql = Dialect.CreateTableSql(Maps.Load<User>());
        Assert.StartsWith("create table if not exists \"users\" (", sql, StringComparison.Ordinal);
        Assert.Contains("\"id\" bigint generated by default as identity primary key", sql, StringComparison.Ordinal);
        Assert.Contains("\"name\" text not null", sql, StringComparison.Ordinal);
        Assert.Contains("\"created_at\" timestamp with time zone not null", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("STRICT", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void Create_table_renders_composite_natural_key()
    {
        var sql = Dialect.CreateTableSql(Maps.Load<UserRole>());
        Assert.Contains("primary key (\"user_id\", \"role_id\")", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void Insert_uses_returning_only_for_generated_keys()
    {
        var users = Dialect.InsertSql(Maps.Load<User>());
        Assert.StartsWith("insert into \"users\" (", users, StringComparison.Ordinal);
        Assert.EndsWith(" returning \"id\"", users, StringComparison.Ordinal);

        Assert.DoesNotContain("returning", Dialect.InsertSql(Maps.Load<UserRole>()), StringComparison.Ordinal);
    }

    [Fact]
    public void Update_bumps_version_and_requires_it()
    {
        var sql = Dialect.UpdateSql(Maps.Load<Transaction>());
        Assert.Contains("\"version\" = \"version\" + 1", sql, StringComparison.Ordinal);
        Assert.EndsWith("where \"id\" = @id and \"version\" = @version", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void Limit_offset_needs_no_workarounds()
    {
        Assert.Equal("limit @l offset @o", Dialect.LimitOffsetClause("@l", "@o"));
        Assert.Equal("limit @l", Dialect.LimitOffsetClause("@l", null));
        Assert.Equal("offset @o", Dialect.LimitOffsetClause(null, "@o"));
    }

    [Fact]
    public void Unordered_paging_stays_plain()
    {
        var bound = new List<object?>();
        var sql = Render(new SelectAst(Maps.Load<User>(), [], [], limit: 2), bound);
        Assert.EndsWith("from \"users\" limit @c0", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("(select null)", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void Select_quotes_identifiers()
    {
        var bound = new List<object?>();
        var ast = new SelectAst(
            Maps.Load<User>(),
            [Criteria.Ge("CreatedAtUtc", TestDb.SeedTime)],
            [new Ordering("Name", SortOrder.Desc)],
            limit: 20,
            offset: 5);
        Assert.Equal(
            "select \"id\", \"name\", \"email\", \"display_name\", \"created_at\", \"updated_at\" from \"users\""
            + " where \"created_at\" >= @c0 order by \"name\" desc limit @c1 offset @c2",
            Render(ast, bound));
        Assert.Equal(3, bound.Count);
    }

    // Composite subquery membership renders as native row-value IN
    // (SupportsRowValueIn = true) — pinned live by PostgresIntegrationTests,
    // Criteria.InSelect being internal.

    [Fact]
    public void Version_table_uses_if_not_exists()
    {
        Assert.StartsWith("create table if not exists schema_version", Dialect.VersionTableSql, StringComparison.Ordinal);
        Assert.Contains("version      bigint not null", Dialect.VersionTableSql, StringComparison.Ordinal);
    }

    [Fact]
    public void Migration_actions_render_ansi_forms_quoted()
    {
        Assert.Equal("alter table \"roles\" rename to \"groups\"", Dialect.RenameTableSql("roles", "groups"));
        Assert.Equal("alter table \"roles\" rename column \"name\" to \"role_name\"", Dialect.RenameColumnSql("roles", "name", "role_name"));
        Assert.Equal("alter table \"users\" add column \"note\" text", Dialect.AddColumnSql("users", "note", "text", nullable: true, defaultSql: null));
        Assert.Equal("alter table \"users\" drop column \"note\"", Dialect.DropColumnSql("users", "note"));
        Assert.Equal("drop table \"users\"", Dialect.DropTableSql("users"));
        Assert.Equal("drop index \"ix_users_email\"", Dialect.DropIndexSql("users", "ix_users_email"));
    }

    [Fact]
    public void Views_and_materialized_views_render_their_own_create()
    {
        Assert.StartsWith(
            "create materialized view if not exists \"monthly_sales_totals\" as",
            Dialect.CreateViewSql(Maps.Load<MonthlySalesTotal>()),
            StringComparison.Ordinal);
        Assert.True(Dialect.SupportsMaterializedViews);
    }

    [Fact]
    public void Storage_types_are_format_type_spellings()
    {
        var transactions = Maps.Load<Transaction>();
        Assert.Equal("numeric", Dialect.StorageType(transactions.Properties.Single(p => p.PropertyName == "Amount")));
        Assert.Equal("text", Dialect.StorageType(transactions.Properties.Single(p => p.PropertyName == "Status")));
        Assert.Equal("timestamp with time zone", Dialect.StorageType(transactions.Properties.Single(p => p.PropertyName == "CreatedAtUtc")));
        Assert.Equal("bigint", Dialect.StorageType(transactions.Properties.Single(p => p.PropertyName == "Id")));
    }

    [Theory]
    [InlineData("text", typeof(string), true)]
    [InlineData("character varying(200)", typeof(string), true)]
    [InlineData("boolean", typeof(bool), true)]
    [InlineData("numeric(12,2)", typeof(decimal), true)]
    [InlineData("timestamp with time zone", typeof(DateTime), true)]
    [InlineData("timestamp(3) with time zone", typeof(DateTime), true)]   // mid-name precision strips
    [InlineData("timestamp without time zone", typeof(DateTime), true)]
    [InlineData("uuid", typeof(Guid), true)]
    [InlineData("integer", typeof(long), true)]
    [InlineData("bigint", typeof(int), false)]   // reading bigint into int can overflow — strict
    [InlineData("text", typeof(int), false)]
    public void Declared_type_compatibility_is_strict(string declared, Type clr, bool compatible)
        => Assert.Equal(compatible, Dialect.IsDeclaredTypeCompatible(declared, clr, enumAsInt: false));
}
